
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CLOSE_LOOP DECREMENT INCREMENT INPUT OPEN_LOOP OUTPUT SHIFT_LEFT SHIFT_RIGHT\n        commands : command\n                 | commands command\n        \n        command : INCREMENT\n                | DECREMENT\n                | SHIFT_LEFT\n                | SHIFT_RIGHT\n                | OUTPUT\n                | INPUT\n                | loop\n        \n        loop : OPEN_LOOP commands CLOSE_LOOP\n        '
    
_lr_action_items = {'INCREMENT':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,],[3,3,-1,-3,-4,-5,-6,-7,-8,-9,3,-2,3,-10,]),'DECREMENT':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,],[4,4,-1,-3,-4,-5,-6,-7,-8,-9,4,-2,4,-10,]),'SHIFT_LEFT':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,],[5,5,-1,-3,-4,-5,-6,-7,-8,-9,5,-2,5,-10,]),'SHIFT_RIGHT':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,],[6,6,-1,-3,-4,-5,-6,-7,-8,-9,6,-2,6,-10,]),'OUTPUT':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,],[7,7,-1,-3,-4,-5,-6,-7,-8,-9,7,-2,7,-10,]),'INPUT':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,],[8,8,-1,-3,-4,-5,-6,-7,-8,-9,8,-2,8,-10,]),'OPEN_LOOP':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,],[10,10,-1,-3,-4,-5,-6,-7,-8,-9,10,-2,10,-10,]),'$end':([1,2,3,4,5,6,7,8,9,11,13,],[0,-1,-3,-4,-5,-6,-7,-8,-9,-2,-10,]),'CLOSE_LOOP':([2,3,4,5,6,7,8,9,11,12,13,],[-1,-3,-4,-5,-6,-7,-8,-9,-2,13,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'commands':([0,10,],[1,12,]),'command':([0,1,10,12,],[2,11,2,11,]),'loop':([0,1,10,12,],[9,9,9,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> commands","S'",1,None,None,None),
  ('commands -> command','commands',1,'p_commands','parser.py',17),
  ('commands -> commands command','commands',2,'p_commands','parser.py',18),
  ('command -> INCREMENT','command',1,'p_command','parser.py',34),
  ('command -> DECREMENT','command',1,'p_command','parser.py',35),
  ('command -> SHIFT_LEFT','command',1,'p_command','parser.py',36),
  ('command -> SHIFT_RIGHT','command',1,'p_command','parser.py',37),
  ('command -> OUTPUT','command',1,'p_command','parser.py',38),
  ('command -> INPUT','command',1,'p_command','parser.py',39),
  ('command -> loop','command',1,'p_command','parser.py',40),
  ('loop -> OPEN_LOOP commands CLOSE_LOOP','loop',3,'p_loop','parser.py',50),
]
